[package]
name = "chronicle"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2021"
description = "IOTA permanode implemented as an IOTA Node Extension (INX)."
readme = "README.md"
repository = "https://github.com/iotaledger/inx-chronicle"
license = "Apache-2.0"
keywords = ["iota", "storage", "permanode", "chronicle", "inx"]
homepage = "https://www.iota.org"

[workspace]
default-members = [".", "bin/inx-chronicle"]
members = [
    ".",
    "bin/inx-chronicle",
]

[dependencies]
inx = { git = "https://github.com/iotaledger/inx", version = "0.2.0", default-features = false }
log = { version = "0.4", default-features = false }
mongodb = { version = "2.1", default-features = false, features = ["tokio-runtime"] }
serde = { version = "1.0", features = ["derive"], default-features = false }
thiserror = { version = "1.0", default-features = false }

# Coerce `indexmap` to use `std` feature. Hopefully this can be removed at some point.
indexmap = { version = "1.8", default-features = false, features = ["std"] }
