[mongodb]
connect_url = "mongodb://localhost:27017"
username = "root"
password = "root"

[inx]
connect_url = "http://localhost:9029"
connection_retry_interval = "5s"

[inx.syncer]
max_simultaneous_requests = 10
sync_back_delta = 10000
sync_back_index = 0

[inx.collector]
num_solidifiers = 10

[api]
port = 9092
allow_origins = ["0.0.0.0"]
