[mongodb]
connect_url = "mongodb://localhost:27017"
username = "root"
password = "root"

[inx]
connect_url = "http://localhost:9029"
connection_retry_interval = "5s"

[api]
port = 9092
allow_origins = ["0.0.0.0"]

[syncer]
max_simultaneous_requests = 10
max_milestones_to_sync = 1000
